### ISSUE TITLE
AttributeError: module 'ruamel.yaml' has no attribute 'YAML'

### ISSUE THREAD

**Issue by rgevaert** [yokogawa-k/docker-ansible-lint#38]
Hi

Since today we are getting these issues:

```
$ ansible-lint --force-color ./ansible/*
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/usr/local/lib/python3.7/site-packages/ansiblelint/__init__.py", line 285, in run
    skip_list=self.skip_list))
  File "/usr/local/lib/python3.7/site-packages/ansiblelint/__init__.py", line 178, in run
    matches.extend(rule.matchyaml(playbookfile, text))
  File "/usr/local/lib/python3.7/site-packages/ansiblelint/__init__.py", line 119, in matchyaml
    yaml = ansiblelint.utils.append_skipped_rules(yaml, text, file['type'])
  File "/usr/local/lib/python3.7/site-packages/ansiblelint/utils.py", line 617, in append_skipped_rules
    yaml_skip = _append_skipped_rules(pyyaml_data, file_text, file_type)
  File "/usr/local/lib/python3.7/site-packages/ansiblelint/utils.py", line 627, in _append_skipped_rules
    yaml = ruamel.yaml.YAML()
AttributeError: module 'ruamel.yaml' has no attribute 'YAML'
```

I'm stilling looking into a solution, but I wanted to already op this ticket to make you aware ;)

**Comment by simschla** [comment]
same here

**Comment by yokogawa-k** [comment]
@rgevaert @simschla 

I'm sorry, everyone.
I made the alpha version of ansible-lint released yesterday as latest. 
I think that is probably the cause.

The current latest is set back to stable v 4.1.0, so please use it.

I'll also add some tests to prevent this from happening.

Thank you for your report.
